import type { Team } from './types';

/**
 * FBS college football: 136 teams (2025 membership). Generated from ESPN public team metadata (FBS standings groups + /college-football/teams/{id}).
 * Static reference data only — no ratings, rosters, or eligibility logic.
 * Logo URLs point at ESPN's public CDN; marks are trademarks of their owners.
 */
export const cfbTeams: readonly Team[] = [
  {
    id: '2005',
    slug: 'air-force-falcons',
    abbreviation: 'AFA',
    location: 'Air Force',
    name: 'Falcons',
    displayName: 'Air Force Falcons',
    group: 'Mountain West',
    color: '#003594',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2005.png',
  },
  {
    id: '2006',
    slug: 'akron-zips',
    abbreviation: 'AKR',
    location: 'Akron',
    name: 'Zips',
    displayName: 'Akron Zips',
    group: 'MAC',
    color: '#041e42',
    alternateColor: '#c5b783',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2006.png',
  },
  {
    id: '333',
    slug: 'alabama-crimson-tide',
    abbreviation: 'ALA',
    location: 'Alabama',
    name: 'Crimson Tide',
    displayName: 'Alabama Crimson Tide',
    group: 'SEC',
    color: '#9e1b32',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png',
  },
  {
    id: '2026',
    slug: 'app-state-mountaineers',
    abbreviation: 'APP',
    location: 'App State',
    name: 'Mountaineers',
    displayName: 'App State Mountaineers',
    group: 'Sun Belt',
    color: '#000000',
    alternateColor: '#ffcd00',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2026.png',
  },
  {
    id: '9',
    slug: 'arizona-state-sun-devils',
    abbreviation: 'ASU',
    location: 'Arizona State',
    name: 'Sun Devils',
    displayName: 'Arizona State Sun Devils',
    group: 'Big 12',
    color: '#ffc627',
    alternateColor: '#8c1d40',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png',
  },
  {
    id: '12',
    slug: 'arizona-wildcats',
    abbreviation: 'ARIZ',
    location: 'Arizona',
    name: 'Wildcats',
    displayName: 'Arizona Wildcats',
    group: 'Big 12',
    color: '#cc0033',
    alternateColor: '#003366',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/12.png',
  },
  {
    id: '8',
    slug: 'arkansas-razorbacks',
    abbreviation: 'ARK',
    location: 'Arkansas',
    name: 'Razorbacks',
    displayName: 'Arkansas Razorbacks',
    group: 'SEC',
    color: '#a32136',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png',
  },
  {
    id: '2032',
    slug: 'arkansas-state-red-wolves',
    abbreviation: 'ARST',
    location: 'Arkansas State',
    name: 'Red Wolves',
    displayName: 'Arkansas State Red Wolves',
    group: 'Sun Belt',
    color: '#cc092f',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2032.png',
  },
  {
    id: '349',
    slug: 'army-black-knights',
    abbreviation: 'ARMY',
    location: 'Army',
    name: 'Black Knights',
    displayName: 'Army Black Knights',
    group: 'American',
    color: '#000000',
    alternateColor: '#d3bc8d',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/349.png',
  },
  {
    id: '2',
    slug: 'auburn-tigers',
    abbreviation: 'AUB',
    location: 'Auburn',
    name: 'Tigers',
    displayName: 'Auburn Tigers',
    group: 'SEC',
    color: '#002b5c',
    alternateColor: '#f26522',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2.png',
  },
  {
    id: '2050',
    slug: 'ball-state-cardinals',
    abbreviation: 'BALL',
    location: 'Ball State',
    name: 'Cardinals',
    displayName: 'Ball State Cardinals',
    group: 'MAC',
    color: '#ba0c2f',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2050.png',
  },
  {
    id: '239',
    slug: 'baylor-bears',
    abbreviation: 'BAY',
    location: 'Baylor',
    name: 'Bears',
    displayName: 'Baylor Bears',
    group: 'Big 12',
    color: '#154734',
    alternateColor: '#ffb81c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/239.png',
  },
  {
    id: '68',
    slug: 'boise-state-broncos',
    abbreviation: 'BOIS',
    location: 'Boise State',
    name: 'Broncos',
    displayName: 'Boise State Broncos',
    group: 'Mountain West',
    color: '#0033a0',
    alternateColor: '#d64309',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/68.png',
  },
  {
    id: '103',
    slug: 'boston-college-eagles',
    abbreviation: 'BC',
    location: 'Boston College',
    name: 'Eagles',
    displayName: 'Boston College Eagles',
    group: 'ACC',
    color: '#8c2232',
    alternateColor: '#dbcca6',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/103.png',
  },
  {
    id: '189',
    slug: 'bowling-green-falcons',
    abbreviation: 'BGSU',
    location: 'Bowling Green',
    name: 'Falcons',
    displayName: 'Bowling Green Falcons',
    group: 'MAC',
    color: '#fd5000',
    alternateColor: '#4f2c1d',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/189.png',
  },
  {
    id: '2084',
    slug: 'buffalo-bulls',
    abbreviation: 'BUFF',
    location: 'Buffalo',
    name: 'Bulls',
    displayName: 'Buffalo Bulls',
    group: 'MAC',
    color: '#005bbb',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2084.png',
  },
  {
    id: '252',
    slug: 'byu-cougars',
    abbreviation: 'BYU',
    location: 'BYU',
    name: 'Cougars',
    displayName: 'BYU Cougars',
    group: 'Big 12',
    color: '#0047ba',
    alternateColor: '#002e5d',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/252.png',
  },
  {
    id: '25',
    slug: 'california-golden-bears',
    abbreviation: 'CAL',
    location: 'California',
    name: 'Golden Bears',
    displayName: 'California Golden Bears',
    group: 'ACC',
    color: '#041e42',
    alternateColor: '#ffc72c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/25.png',
  },
  {
    id: '2117',
    slug: 'central-michigan-chippewas',
    abbreviation: 'CMU',
    location: 'Central Michigan',
    name: 'Chippewas',
    displayName: 'Central Michigan Chippewas',
    group: 'MAC',
    color: '#4c0027',
    alternateColor: '#fbab18',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2117.png',
  },
  {
    id: '2429',
    slug: 'charlotte-49ers',
    abbreviation: 'CLT',
    location: 'Charlotte',
    name: '49ers',
    displayName: 'Charlotte 49ers',
    group: 'American',
    color: '#005035',
    alternateColor: '#a49665',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2429.png',
  },
  {
    id: '2132',
    slug: 'cincinnati-bearcats',
    abbreviation: 'CIN',
    location: 'Cincinnati',
    name: 'Bearcats',
    displayName: 'Cincinnati Bearcats',
    group: 'Big 12',
    color: '#000000',
    alternateColor: '#e00122',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2132.png',
  },
  {
    id: '228',
    slug: 'clemson-tigers',
    abbreviation: 'CLEM',
    location: 'Clemson',
    name: 'Tigers',
    displayName: 'Clemson Tigers',
    group: 'ACC',
    color: '#f56600',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/228.png',
  },
  {
    id: '324',
    slug: 'coastal-carolina-chanticleers',
    abbreviation: 'CCU',
    location: 'Coastal Carolina',
    name: 'Chanticleers',
    displayName: 'Coastal Carolina Chanticleers',
    group: 'Sun Belt',
    color: '#006f71',
    alternateColor: '#a27752',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/324.png',
  },
  {
    id: '38',
    slug: 'colorado-buffaloes',
    abbreviation: 'COLO',
    location: 'Colorado',
    name: 'Buffaloes',
    displayName: 'Colorado Buffaloes',
    group: 'Big 12',
    color: '#cfb87c',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/38.png',
  },
  {
    id: '36',
    slug: 'colorado-state-rams',
    abbreviation: 'CSU',
    location: 'Colorado State',
    name: 'Rams',
    displayName: 'Colorado State Rams',
    group: 'Mountain West',
    color: '#004c23',
    alternateColor: '#c8c372',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/36.png',
  },
  {
    id: '48',
    slug: 'delaware-blue-hens',
    abbreviation: 'DEL',
    location: 'Delaware',
    name: 'Blue Hens',
    displayName: 'Delaware Blue Hens',
    group: 'Conference USA',
    color: '#00539f',
    alternateColor: '#ffd200',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/48.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/48.png',
  },
  {
    id: '150',
    slug: 'duke-blue-devils',
    abbreviation: 'DUKE',
    location: 'Duke',
    name: 'Blue Devils',
    displayName: 'Duke Blue Devils',
    group: 'ACC',
    color: '#00539b',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/150.png',
  },
  {
    id: '151',
    slug: 'east-carolina-pirates',
    abbreviation: 'ECU',
    location: 'East Carolina',
    name: 'Pirates',
    displayName: 'East Carolina Pirates',
    group: 'American',
    color: '#582c83',
    alternateColor: '#ffc72c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/151.png',
  },
  {
    id: '2199',
    slug: 'eastern-michigan-eagles',
    abbreviation: 'EMU',
    location: 'Eastern Michigan',
    name: 'Eagles',
    displayName: 'Eastern Michigan Eagles',
    group: 'MAC',
    color: '#006938',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2199.png',
  },
  {
    id: '2226',
    slug: 'florida-atlantic-owls',
    abbreviation: 'FAU',
    location: 'Florida Atlantic',
    name: 'Owls',
    displayName: 'Florida Atlantic Owls',
    group: 'American',
    color: '#003366',
    alternateColor: '#cc0000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png',
  },
  {
    id: '57',
    slug: 'florida-gators',
    abbreviation: 'FLA',
    location: 'Florida',
    name: 'Gators',
    displayName: 'Florida Gators',
    group: 'SEC',
    color: '#0021a5',
    alternateColor: '#fa4616',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/57.png',
  },
  {
    id: '2229',
    slug: 'florida-international-panthers',
    abbreviation: 'FIU',
    location: 'Florida International',
    name: 'Panthers',
    displayName: 'Florida International Panthers',
    group: 'Conference USA',
    color: '#091f3f',
    alternateColor: '#c3993f',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2229.png',
  },
  {
    id: '52',
    slug: 'florida-state-seminoles',
    abbreviation: 'FSU',
    location: 'Florida State',
    name: 'Seminoles',
    displayName: 'Florida State Seminoles',
    group: 'ACC',
    color: '#782f40',
    alternateColor: '#ceb888',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/52.png',
  },
  {
    id: '278',
    slug: 'fresno-state-bulldogs',
    abbreviation: 'FRES',
    location: 'Fresno State',
    name: 'Bulldogs',
    displayName: 'Fresno State Bulldogs',
    group: 'Mountain West',
    color: '#b1102b',
    alternateColor: '#13284c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/278.png',
  },
  {
    id: '61',
    slug: 'georgia-bulldogs',
    abbreviation: 'UGA',
    location: 'Georgia',
    name: 'Bulldogs',
    displayName: 'Georgia Bulldogs',
    group: 'SEC',
    color: '#ba0c2f',
    alternateColor: '#2c2a29',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/61.png',
  },
  {
    id: '290',
    slug: 'georgia-southern-eagles',
    abbreviation: 'GASO',
    location: 'Georgia Southern',
    name: 'Eagles',
    displayName: 'Georgia Southern Eagles',
    group: 'Sun Belt',
    color: '#041e42',
    alternateColor: '#a3aaae',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/290.png',
  },
  {
    id: '2247',
    slug: 'georgia-state-panthers',
    abbreviation: 'GAST',
    location: 'Georgia State',
    name: 'Panthers',
    displayName: 'Georgia State Panthers',
    group: 'Sun Belt',
    color: '#0039a6',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2247.png',
  },
  {
    id: '59',
    slug: 'georgia-tech-yellow-jackets',
    abbreviation: 'GT',
    location: 'Georgia Tech',
    name: 'Yellow Jackets',
    displayName: 'Georgia Tech Yellow Jackets',
    group: 'ACC',
    color: '#b3a369',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/59.png',
  },
  {
    id: '62',
    slug: 'hawaii-rainbow-warriors',
    abbreviation: 'HAW',
    location: "Hawai'i",
    name: 'Rainbow Warriors',
    displayName: "Hawai'i Rainbow Warriors",
    group: 'Mountain West',
    color: '#005737',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/62.png',
  },
  {
    id: '248',
    slug: 'houston-cougars',
    abbreviation: 'HOU',
    location: 'Houston',
    name: 'Cougars',
    displayName: 'Houston Cougars',
    group: 'Big 12',
    color: '#c8102e',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png',
  },
  {
    id: '356',
    slug: 'illinois-fighting-illini',
    abbreviation: 'ILL',
    location: 'Illinois',
    name: 'Fighting Illini',
    displayName: 'Illinois Fighting Illini',
    group: 'Big Ten',
    color: '#ff5f05',
    alternateColor: '#13294b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/356.png',
  },
  {
    id: '84',
    slug: 'indiana-hoosiers',
    abbreviation: 'IU',
    location: 'Indiana',
    name: 'Hoosiers',
    displayName: 'Indiana Hoosiers',
    group: 'Big Ten',
    color: '#970310',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png',
  },
  {
    id: '2294',
    slug: 'iowa-hawkeyes',
    abbreviation: 'IOWA',
    location: 'Iowa',
    name: 'Hawkeyes',
    displayName: 'Iowa Hawkeyes',
    group: 'Big Ten',
    color: '#231f20',
    alternateColor: '#fcd116',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2294.png',
  },
  {
    id: '66',
    slug: 'iowa-state-cyclones',
    abbreviation: 'ISU',
    location: 'Iowa State',
    name: 'Cyclones',
    displayName: 'Iowa State Cyclones',
    group: 'Big 12',
    color: '#ae192d',
    alternateColor: '#ffc72a',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/66.png',
  },
  {
    id: '55',
    slug: 'jacksonville-state-gamecocks',
    abbreviation: 'JVST',
    location: 'Jacksonville State',
    name: 'Gamecocks',
    displayName: 'Jacksonville State Gamecocks',
    group: 'Conference USA',
    color: '#cc0000',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/55.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/55.png',
  },
  {
    id: '256',
    slug: 'james-madison-dukes',
    abbreviation: 'JMU',
    location: 'James Madison',
    name: 'Dukes',
    displayName: 'James Madison Dukes',
    group: 'Sun Belt',
    color: '#450084',
    alternateColor: '#cbb677',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/256.png',
  },
  {
    id: '2305',
    slug: 'kansas-jayhawks',
    abbreviation: 'KU',
    location: 'Kansas',
    name: 'Jayhawks',
    displayName: 'Kansas Jayhawks',
    group: 'Big 12',
    color: '#0051ba',
    alternateColor: '#e8000d',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2305.png',
  },
  {
    id: '2306',
    slug: 'kansas-state-wildcats',
    abbreviation: 'KSU',
    location: 'Kansas State',
    name: 'Wildcats',
    displayName: 'Kansas State Wildcats',
    group: 'Big 12',
    color: '#330a57',
    alternateColor: '#e2e3e4',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png',
  },
  {
    id: '338',
    slug: 'kennesaw-state-owls',
    abbreviation: 'KENN',
    location: 'Kennesaw State',
    name: 'Owls',
    displayName: 'Kennesaw State Owls',
    group: 'Conference USA',
    color: '#fdbb30',
    alternateColor: '#0b1315',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/338.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/338.png',
  },
  {
    id: '2309',
    slug: 'kent-state-golden-flashes',
    abbreviation: 'KENT',
    location: 'Kent State',
    name: 'Golden Flashes',
    displayName: 'Kent State Golden Flashes',
    group: 'MAC',
    color: '#002664',
    alternateColor: '#eaab00',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2309.png',
  },
  {
    id: '96',
    slug: 'kentucky-wildcats',
    abbreviation: 'UK',
    location: 'Kentucky',
    name: 'Wildcats',
    displayName: 'Kentucky Wildcats',
    group: 'SEC',
    color: '#0033a0',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/96.png',
  },
  {
    id: '2335',
    slug: 'liberty-flames',
    abbreviation: 'LIB',
    location: 'Liberty',
    name: 'Flames',
    displayName: 'Liberty Flames',
    group: 'Conference USA',
    color: '#0a254e',
    alternateColor: '#b72025',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2335.png',
  },
  {
    id: '309',
    slug: 'louisiana-ragin-cajuns',
    abbreviation: 'UL',
    location: 'Louisiana',
    name: "Ragin' Cajuns",
    displayName: "Louisiana Ragin' Cajuns",
    group: 'Sun Belt',
    color: '#ce181e',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/309.png',
  },
  {
    id: '2348',
    slug: 'louisiana-tech-bulldogs',
    abbreviation: 'LT',
    location: 'Louisiana Tech',
    name: 'Bulldogs',
    displayName: 'Louisiana Tech Bulldogs',
    group: 'Conference USA',
    color: '#003087',
    alternateColor: '#cb333b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2348.png',
  },
  {
    id: '97',
    slug: 'louisville-cardinals',
    abbreviation: 'LOU',
    location: 'Louisville',
    name: 'Cardinals',
    displayName: 'Louisville Cardinals',
    group: 'ACC',
    color: '#c9001f',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/97.png',
  },
  {
    id: '99',
    slug: 'lsu-tigers',
    abbreviation: 'LSU',
    location: 'LSU',
    name: 'Tigers',
    displayName: 'LSU Tigers',
    group: 'SEC',
    color: '#461d76',
    alternateColor: '#fdd023',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/99.png',
  },
  {
    id: '276',
    slug: 'marshall-thundering-herd',
    abbreviation: 'MRSH',
    location: 'Marshall',
    name: 'Thundering Herd',
    displayName: 'Marshall Thundering Herd',
    group: 'Sun Belt',
    color: '#00b140',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/276.png',
  },
  {
    id: '120',
    slug: 'maryland-terrapins',
    abbreviation: 'MD',
    location: 'Maryland',
    name: 'Terrapins',
    displayName: 'Maryland Terrapins',
    group: 'Big Ten',
    color: '#ce1126',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/120.png',
  },
  {
    id: '113',
    slug: 'massachusetts-minutemen',
    abbreviation: 'MASS',
    location: 'Massachusetts',
    name: 'Minutemen',
    displayName: 'Massachusetts Minutemen',
    group: 'MAC',
    color: '#881c1c',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/113.png',
  },
  {
    id: '235',
    slug: 'memphis-tigers',
    abbreviation: 'MEM',
    location: 'Memphis',
    name: 'Tigers',
    displayName: 'Memphis Tigers',
    group: 'American',
    color: '#004991',
    alternateColor: '#8e908f',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/235.png',
  },
  {
    id: '193',
    slug: 'miami-oh-redhawks',
    abbreviation: 'M-OH',
    location: 'Miami (OH)',
    name: 'RedHawks',
    displayName: 'Miami (OH) RedHawks',
    group: 'MAC',
    color: '#c41230',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/193.png',
  },
  {
    id: '2390',
    slug: 'miami-hurricanes',
    abbreviation: 'MIA',
    location: 'Miami',
    name: 'Hurricanes',
    displayName: 'Miami Hurricanes',
    group: 'ACC',
    color: '#f47423',
    alternateColor: '#035131',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png',
  },
  {
    id: '127',
    slug: 'michigan-state-spartans',
    abbreviation: 'MSU',
    location: 'Michigan State',
    name: 'Spartans',
    displayName: 'Michigan State Spartans',
    group: 'Big Ten',
    color: '#173f35',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/127.png',
  },
  {
    id: '130',
    slug: 'michigan-wolverines',
    abbreviation: 'MICH',
    location: 'Michigan',
    name: 'Wolverines',
    displayName: 'Michigan Wolverines',
    group: 'Big Ten',
    color: '#00274c',
    alternateColor: '#ffcb05',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/130.png',
  },
  {
    id: '2393',
    slug: 'middle-tennessee-blue-raiders',
    abbreviation: 'MTSU',
    location: 'Middle Tennessee',
    name: 'Blue Raiders',
    displayName: 'Middle Tennessee Blue Raiders',
    group: 'Conference USA',
    color: '#036eb7',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2393.png',
  },
  {
    id: '135',
    slug: 'minnesota-golden-gophers',
    abbreviation: 'MINN',
    location: 'Minnesota',
    name: 'Golden Gophers',
    displayName: 'Minnesota Golden Gophers',
    group: 'Big Ten',
    color: '#5e0a2f',
    alternateColor: '#fab41c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/135.png',
  },
  {
    id: '344',
    slug: 'mississippi-state-bulldogs',
    abbreviation: 'MSST',
    location: 'Mississippi State',
    name: 'Bulldogs',
    displayName: 'Mississippi State Bulldogs',
    group: 'SEC',
    color: '#5d1725',
    alternateColor: '#c1c6c8',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/344.png',
  },
  {
    id: '2623',
    slug: 'missouri-state-bears',
    abbreviation: 'MOST',
    location: 'Missouri State',
    name: 'Bears',
    displayName: 'Missouri State Bears',
    group: 'Conference USA',
    color: '#5e0009',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2623.png',
  },
  {
    id: '142',
    slug: 'missouri-tigers',
    abbreviation: 'MIZ',
    location: 'Missouri',
    name: 'Tigers',
    displayName: 'Missouri Tigers',
    group: 'SEC',
    color: '#f1b82d',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/142.png',
  },
  {
    id: '2426',
    slug: 'navy-midshipmen',
    abbreviation: 'NAVY',
    location: 'Navy',
    name: 'Midshipmen',
    displayName: 'Navy Midshipmen',
    group: 'American',
    color: '#00225b',
    alternateColor: '#b5a67c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2426.png',
  },
  {
    id: '152',
    slug: 'nc-state-wolfpack',
    abbreviation: 'NCSU',
    location: 'NC State',
    name: 'Wolfpack',
    displayName: 'NC State Wolfpack',
    group: 'ACC',
    color: '#cc0000',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/152.png',
  },
  {
    id: '158',
    slug: 'nebraska-cornhuskers',
    abbreviation: 'NEB',
    location: 'Nebraska',
    name: 'Cornhuskers',
    displayName: 'Nebraska Cornhuskers',
    group: 'Big Ten',
    color: '#e31937',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/158.png',
  },
  {
    id: '2440',
    slug: 'nevada-wolf-pack',
    abbreviation: 'NEV',
    location: 'Nevada',
    name: 'Wolf Pack',
    displayName: 'Nevada Wolf Pack',
    group: 'Mountain West',
    color: '#041e42',
    alternateColor: '#8a8d8f',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2440.png',
  },
  {
    id: '167',
    slug: 'new-mexico-lobos',
    abbreviation: 'UNM',
    location: 'New Mexico',
    name: 'Lobos',
    displayName: 'New Mexico Lobos',
    group: 'Mountain West',
    color: '#ba0c2f',
    alternateColor: '#a7a8aa',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/167.png',
  },
  {
    id: '166',
    slug: 'new-mexico-state-aggies',
    abbreviation: 'NMSU',
    location: 'New Mexico State',
    name: 'Aggies',
    displayName: 'New Mexico State Aggies',
    group: 'Conference USA',
    color: '#7e141b',
    alternateColor: '#231f20',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/166.png',
  },
  {
    id: '153',
    slug: 'north-carolina-tar-heels',
    abbreviation: 'UNC',
    location: 'North Carolina',
    name: 'Tar Heels',
    displayName: 'North Carolina Tar Heels',
    group: 'ACC',
    color: '#7bafd4',
    alternateColor: '#13294b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/153.png',
  },
  {
    id: '249',
    slug: 'north-texas-mean-green',
    abbreviation: 'UNT',
    location: 'North Texas',
    name: 'Mean Green',
    displayName: 'North Texas Mean Green',
    group: 'American',
    color: '#068f33',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/249.png',
  },
  {
    id: '2459',
    slug: 'northern-illinois-huskies',
    abbreviation: 'NIU',
    location: 'Northern Illinois',
    name: 'Huskies',
    displayName: 'Northern Illinois Huskies',
    group: 'MAC',
    color: '#c8102e',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2459.png',
  },
  {
    id: '77',
    slug: 'northwestern-wildcats',
    abbreviation: 'NU',
    location: 'Northwestern',
    name: 'Wildcats',
    displayName: 'Northwestern Wildcats',
    group: 'Big Ten',
    color: '#492f92',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/77.png',
  },
  {
    id: '87',
    slug: 'notre-dame-fighting-irish',
    abbreviation: 'ND',
    location: 'Notre Dame',
    name: 'Fighting Irish',
    displayName: 'Notre Dame Fighting Irish',
    group: 'Independent',
    color: '#062340',
    alternateColor: '#c99700',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/87.png',
  },
  {
    id: '195',
    slug: 'ohio-bobcats',
    abbreviation: 'OHIO',
    location: 'Ohio',
    name: 'Bobcats',
    displayName: 'Ohio Bobcats',
    group: 'MAC',
    color: '#154734',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/195.png',
  },
  {
    id: '194',
    slug: 'ohio-state-buckeyes',
    abbreviation: 'OSU',
    location: 'Ohio State',
    name: 'Buckeyes',
    displayName: 'Ohio State Buckeyes',
    group: 'Big Ten',
    color: '#ba0c2f',
    alternateColor: '#a8adb4',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/194.png',
  },
  {
    id: '201',
    slug: 'oklahoma-sooners',
    abbreviation: 'OU',
    location: 'Oklahoma',
    name: 'Sooners',
    displayName: 'Oklahoma Sooners',
    group: 'SEC',
    color: '#990000',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/201.png',
  },
  {
    id: '197',
    slug: 'oklahoma-state-cowboys',
    abbreviation: 'OKST',
    location: 'Oklahoma State',
    name: 'Cowboys',
    displayName: 'Oklahoma State Cowboys',
    group: 'Big 12',
    color: '#fe5c00',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/197.png',
  },
  {
    id: '295',
    slug: 'old-dominion-monarchs',
    abbreviation: 'ODU',
    location: 'Old Dominion',
    name: 'Monarchs',
    displayName: 'Old Dominion Monarchs',
    group: 'Sun Belt',
    color: '#003768',
    alternateColor: '#a1d2f1',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/295.png',
  },
  {
    id: '145',
    slug: 'ole-miss-rebels',
    abbreviation: 'MISS',
    location: 'Ole Miss',
    name: 'Rebels',
    displayName: 'Ole Miss Rebels',
    group: 'SEC',
    color: '#13294b',
    alternateColor: '#cf142b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/145.png',
  },
  {
    id: '2483',
    slug: 'oregon-ducks',
    abbreviation: 'ORE',
    location: 'Oregon',
    name: 'Ducks',
    displayName: 'Oregon Ducks',
    group: 'Big Ten',
    color: '#00934b',
    alternateColor: '#fff41b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2483.png',
  },
  {
    id: '204',
    slug: 'oregon-state-beavers',
    abbreviation: 'ORST',
    location: 'Oregon State',
    name: 'Beavers',
    displayName: 'Oregon State Beavers',
    group: 'Pac-12',
    color: '#dc4405',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/204.png',
  },
  {
    id: '213',
    slug: 'penn-state-nittany-lions',
    abbreviation: 'PSU',
    location: 'Penn State',
    name: 'Nittany Lions',
    displayName: 'Penn State Nittany Lions',
    group: 'Big Ten',
    color: '#061440',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png',
  },
  {
    id: '221',
    slug: 'pittsburgh-panthers',
    abbreviation: 'PITT',
    location: 'Pittsburgh',
    name: 'Panthers',
    displayName: 'Pittsburgh Panthers',
    group: 'ACC',
    color: '#003594',
    alternateColor: '#ffb81c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/221.png',
  },
  {
    id: '2509',
    slug: 'purdue-boilermakers',
    abbreviation: 'PUR',
    location: 'Purdue',
    name: 'Boilermakers',
    displayName: 'Purdue Boilermakers',
    group: 'Big Ten',
    color: '#ceb888',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2509.png',
  },
  {
    id: '242',
    slug: 'rice-owls',
    abbreviation: 'RICE',
    location: 'Rice',
    name: 'Owls',
    displayName: 'Rice Owls',
    group: 'American',
    color: '#00205b',
    alternateColor: '#c1c6c8',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/242.png',
  },
  {
    id: '164',
    slug: 'rutgers-scarlet-knights',
    abbreviation: 'RUTG',
    location: 'Rutgers',
    name: 'Scarlet Knights',
    displayName: 'Rutgers Scarlet Knights',
    group: 'Big Ten',
    color: '#ce0e2d',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/164.png',
  },
  {
    id: '2534',
    slug: 'sam-houston-bearkats',
    abbreviation: 'SHSU',
    location: 'Sam Houston',
    name: 'Bearkats',
    displayName: 'Sam Houston Bearkats',
    group: 'Conference USA',
    color: '#f56423',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2534.png',
  },
  {
    id: '21',
    slug: 'san-diego-state-aztecs',
    abbreviation: 'SDSU',
    location: 'San Diego State',
    name: 'Aztecs',
    displayName: 'San Diego State Aztecs',
    group: 'Mountain West',
    color: '#a6192e',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png',
  },
  {
    id: '23',
    slug: 'san-jose-state-spartans',
    abbreviation: 'SJSU',
    location: 'San José State',
    name: 'Spartans',
    displayName: 'San José State Spartans',
    group: 'Mountain West',
    color: '#0038a8',
    alternateColor: '#ffb81a',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/23.png',
  },
  {
    id: '2567',
    slug: 'smu-mustangs',
    abbreviation: 'SMU',
    location: 'SMU',
    name: 'Mustangs',
    displayName: 'SMU Mustangs',
    group: 'ACC',
    color: '#a80000',
    alternateColor: '#0033a1',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2567.png',
  },
  {
    id: '6',
    slug: 'south-alabama-jaguars',
    abbreviation: 'USA',
    location: 'South Alabama',
    name: 'Jaguars',
    displayName: 'South Alabama Jaguars',
    group: 'Sun Belt',
    color: '#00205b',
    alternateColor: '#bf0d3e',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/6.png',
  },
  {
    id: '2579',
    slug: 'south-carolina-gamecocks',
    abbreviation: 'SC',
    location: 'South Carolina',
    name: 'Gamecocks',
    displayName: 'South Carolina Gamecocks',
    group: 'SEC',
    color: '#73000a',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2579.png',
  },
  {
    id: '58',
    slug: 'south-florida-bulls',
    abbreviation: 'USF',
    location: 'South Florida',
    name: 'Bulls',
    displayName: 'South Florida Bulls',
    group: 'American',
    color: '#006747',
    alternateColor: '#cfc493',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/58.png',
  },
  {
    id: '2572',
    slug: 'southern-miss-golden-eagles',
    abbreviation: 'USM',
    location: 'Southern Miss',
    name: 'Golden Eagles',
    displayName: 'Southern Miss Golden Eagles',
    group: 'Sun Belt',
    color: '#ffc72c',
    alternateColor: '#231f20',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2572.png',
  },
  {
    id: '24',
    slug: 'stanford-cardinal',
    abbreviation: 'STAN',
    location: 'Stanford',
    name: 'Cardinal',
    displayName: 'Stanford Cardinal',
    group: 'ACC',
    color: '#8c1515',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/24.png',
  },
  {
    id: '183',
    slug: 'syracuse-orange',
    abbreviation: 'SYR',
    location: 'Syracuse',
    name: 'Orange',
    displayName: 'Syracuse Orange',
    group: 'ACC',
    color: '#000e54',
    alternateColor: '#ff431b',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/183.png',
  },
  {
    id: '2628',
    slug: 'tcu-horned-frogs',
    abbreviation: 'TCU',
    location: 'TCU',
    name: 'Horned Frogs',
    displayName: 'TCU Horned Frogs',
    group: 'Big 12',
    color: '#4d1979',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2628.png',
  },
  {
    id: '218',
    slug: 'temple-owls',
    abbreviation: 'TEM',
    location: 'Temple',
    name: 'Owls',
    displayName: 'Temple Owls',
    group: 'American',
    color: '#a41e35',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/218.png',
  },
  {
    id: '2633',
    slug: 'tennessee-volunteers',
    abbreviation: 'TENN',
    location: 'Tennessee',
    name: 'Volunteers',
    displayName: 'Tennessee Volunteers',
    group: 'SEC',
    color: '#ff8200',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png',
  },
  {
    id: '245',
    slug: 'texas-am-aggies',
    abbreviation: 'TA&M',
    location: 'Texas A&M',
    name: 'Aggies',
    displayName: 'Texas A&M Aggies',
    group: 'SEC',
    color: '#500000',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/245.png',
  },
  {
    id: '251',
    slug: 'texas-longhorns',
    abbreviation: 'TEX',
    location: 'Texas',
    name: 'Longhorns',
    displayName: 'Texas Longhorns',
    group: 'SEC',
    color: '#af5c37',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png',
  },
  {
    id: '326',
    slug: 'texas-state-bobcats',
    abbreviation: 'TXST',
    location: 'Texas State',
    name: 'Bobcats',
    displayName: 'Texas State Bobcats',
    group: 'Sun Belt',
    color: '#501214',
    alternateColor: '#6a5638',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/326.png',
  },
  {
    id: '2641',
    slug: 'texas-tech-red-raiders',
    abbreviation: 'TTU',
    location: 'Texas Tech',
    name: 'Red Raiders',
    displayName: 'Texas Tech Red Raiders',
    group: 'Big 12',
    color: '#da291c',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2641.png',
  },
  {
    id: '2649',
    slug: 'toledo-rockets',
    abbreviation: 'TOL',
    location: 'Toledo',
    name: 'Rockets',
    displayName: 'Toledo Rockets',
    group: 'MAC',
    color: '#0b2240',
    alternateColor: '#ffcd00',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2649.png',
  },
  {
    id: '2653',
    slug: 'troy-trojans',
    abbreviation: 'TROY',
    location: 'Troy',
    name: 'Trojans',
    displayName: 'Troy Trojans',
    group: 'Sun Belt',
    color: '#862633',
    alternateColor: '#b1b1b1',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2653.png',
  },
  {
    id: '2655',
    slug: 'tulane-green-wave',
    abbreviation: 'TULN',
    location: 'Tulane',
    name: 'Green Wave',
    displayName: 'Tulane Green Wave',
    group: 'American',
    color: '#006747',
    alternateColor: '#418fde',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2655.png',
  },
  {
    id: '202',
    slug: 'tulsa-golden-hurricane',
    abbreviation: 'TLSA',
    location: 'Tulsa',
    name: 'Golden Hurricane',
    displayName: 'Tulsa Golden Hurricane',
    group: 'American',
    color: '#003595',
    alternateColor: '#d0b787',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/202.png',
  },
  {
    id: '5',
    slug: 'uab-blazers',
    abbreviation: 'UAB',
    location: 'UAB',
    name: 'Blazers',
    displayName: 'UAB Blazers',
    group: 'American',
    color: '#1a5632',
    alternateColor: '#fdb913',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/5.png',
  },
  {
    id: '2116',
    slug: 'ucf-knights',
    abbreviation: 'UCF',
    location: 'UCF',
    name: 'Knights',
    displayName: 'UCF Knights',
    group: 'Big 12',
    color: '#000000',
    alternateColor: '#b4a169',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2116.png',
  },
  {
    id: '26',
    slug: 'ucla-bruins',
    abbreviation: 'UCLA',
    location: 'UCLA',
    name: 'Bruins',
    displayName: 'UCLA Bruins',
    group: 'Big Ten',
    color: '#2774ae',
    alternateColor: '#f2a900',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png',
  },
  {
    id: '41',
    slug: 'uconn-huskies',
    abbreviation: 'CONN',
    location: 'UConn',
    name: 'Huskies',
    displayName: 'UConn Huskies',
    group: 'Independent',
    color: '#0c2340',
    alternateColor: '#a2aaad',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png',
  },
  {
    id: '2433',
    slug: 'ul-monroe-warhawks',
    abbreviation: 'ULM',
    location: 'UL Monroe',
    name: 'Warhawks',
    displayName: 'UL Monroe Warhawks',
    group: 'Sun Belt',
    color: '#840029',
    alternateColor: '#fdb913',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2433.png',
  },
  {
    id: '2439',
    slug: 'unlv-rebels',
    abbreviation: 'UNLV',
    location: 'UNLV',
    name: 'Rebels',
    displayName: 'UNLV Rebels',
    group: 'Mountain West',
    color: '#cf0a2c',
    alternateColor: '#cac8c8',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2439.png',
  },
  {
    id: '30',
    slug: 'usc-trojans',
    abbreviation: 'USC',
    location: 'USC',
    name: 'Trojans',
    displayName: 'USC Trojans',
    group: 'Big Ten',
    color: '#9d2235',
    alternateColor: '#ffc72c',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/30.png',
  },
  {
    id: '328',
    slug: 'utah-state-aggies',
    abbreviation: 'USU',
    location: 'Utah State',
    name: 'Aggies',
    displayName: 'Utah State Aggies',
    group: 'Mountain West',
    color: '#0f2439',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/328.png',
  },
  {
    id: '254',
    slug: 'utah-utes',
    abbreviation: 'UTAH',
    location: 'Utah',
    name: 'Utes',
    displayName: 'Utah Utes',
    group: 'Big 12',
    color: '#be0000',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/254.png',
  },
  {
    id: '2638',
    slug: 'utep-miners',
    abbreviation: 'UTEP',
    location: 'UTEP',
    name: 'Miners',
    displayName: 'UTEP Miners',
    group: 'Conference USA',
    color: '#ff8200',
    alternateColor: '#041e42',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2638.png',
  },
  {
    id: '2636',
    slug: 'utsa-roadrunners',
    abbreviation: 'UTSA',
    location: 'UTSA',
    name: 'Roadrunners',
    displayName: 'UTSA Roadrunners',
    group: 'American',
    color: '#0c2340',
    alternateColor: '#f15a22',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2636.png',
  },
  {
    id: '238',
    slug: 'vanderbilt-commodores',
    abbreviation: 'VAN',
    location: 'Vanderbilt',
    name: 'Commodores',
    displayName: 'Vanderbilt Commodores',
    group: 'SEC',
    color: '#000000',
    alternateColor: '#cfae70',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/238.png',
  },
  {
    id: '258',
    slug: 'virginia-cavaliers',
    abbreviation: 'UVA',
    location: 'Virginia',
    name: 'Cavaliers',
    displayName: 'Virginia Cavaliers',
    group: 'ACC',
    color: '#232d4b',
    alternateColor: '#f84c1e',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/258.png',
  },
  {
    id: '259',
    slug: 'virginia-tech-hokies',
    abbreviation: 'VT',
    location: 'Virginia Tech',
    name: 'Hokies',
    displayName: 'Virginia Tech Hokies',
    group: 'ACC',
    color: '#6a2c3e',
    alternateColor: '#cf4520',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/259.png',
  },
  {
    id: '154',
    slug: 'wake-forest-demon-deacons',
    abbreviation: 'WAKE',
    location: 'Wake Forest',
    name: 'Demon Deacons',
    displayName: 'Wake Forest Demon Deacons',
    group: 'ACC',
    color: '#ceb888',
    alternateColor: '#2c2a29',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/154.png',
  },
  {
    id: '264',
    slug: 'washington-huskies',
    abbreviation: 'WASH',
    location: 'Washington',
    name: 'Huskies',
    displayName: 'Washington Huskies',
    group: 'Big Ten',
    color: '#33006f',
    alternateColor: '#e8d3a2',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/264.png',
  },
  {
    id: '265',
    slug: 'washington-state-cougars',
    abbreviation: 'WSU',
    location: 'Washington State',
    name: 'Cougars',
    displayName: 'Washington State Cougars',
    group: 'Pac-12',
    color: '#a60f2d',
    alternateColor: '#4d4d4d',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/265.png',
  },
  {
    id: '277',
    slug: 'west-virginia-mountaineers',
    abbreviation: 'WVU',
    location: 'West Virginia',
    name: 'Mountaineers',
    displayName: 'West Virginia Mountaineers',
    group: 'Big 12',
    color: '#eaaa00',
    alternateColor: '#002855',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/277.png',
  },
  {
    id: '98',
    slug: 'western-kentucky-hilltoppers',
    abbreviation: 'WKU',
    location: 'Western Kentucky',
    name: 'Hilltoppers',
    displayName: 'Western Kentucky Hilltoppers',
    group: 'Conference USA',
    color: '#e13a3e',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/98.png',
  },
  {
    id: '2711',
    slug: 'western-michigan-broncos',
    abbreviation: 'WMU',
    location: 'Western Michigan',
    name: 'Broncos',
    displayName: 'Western Michigan Broncos',
    group: 'MAC',
    color: '#532e1f',
    alternateColor: '#f1c500',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2711.png',
  },
  {
    id: '275',
    slug: 'wisconsin-badgers',
    abbreviation: 'WIS',
    location: 'Wisconsin',
    name: 'Badgers',
    displayName: 'Wisconsin Badgers',
    group: 'Big Ten',
    color: '#a00000',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/275.png',
  },
  {
    id: '2751',
    slug: 'wyoming-cowboys',
    abbreviation: 'WYO',
    location: 'Wyoming',
    name: 'Cowboys',
    displayName: 'Wyoming Cowboys',
    group: 'Mountain West',
    color: '#492f24',
    alternateColor: '#ffc425',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2751.png',
  },
];
