import type { Team } from './types';

/**
 * NFL: 32 teams. Generated from ESPN public team metadata (/nfl/teams).
 * Static reference data only — no ratings, rosters, or eligibility logic.
 * Logo URLs point at ESPN's public CDN; marks are trademarks of their owners.
 */
export const nflTeams: readonly Team[] = [
  {
    id: '22',
    slug: 'arizona-cardinals',
    abbreviation: 'ARI',
    location: 'Arizona',
    name: 'Cardinals',
    displayName: 'Arizona Cardinals',
    group: 'NFC West',
    color: '#a40227',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/ari.png',
  },
  {
    id: '1',
    slug: 'atlanta-falcons',
    abbreviation: 'ATL',
    location: 'Atlanta',
    name: 'Falcons',
    displayName: 'Atlanta Falcons',
    group: 'NFC South',
    color: '#a71930',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/atl.png',
  },
  {
    id: '33',
    slug: 'baltimore-ravens',
    abbreviation: 'BAL',
    location: 'Baltimore',
    name: 'Ravens',
    displayName: 'Baltimore Ravens',
    group: 'AFC North',
    color: '#29126f',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/bal.png',
  },
  {
    id: '2',
    slug: 'buffalo-bills',
    abbreviation: 'BUF',
    location: 'Buffalo',
    name: 'Bills',
    displayName: 'Buffalo Bills',
    group: 'AFC East',
    color: '#00338d',
    alternateColor: '#d50a0a',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/buf.png',
  },
  {
    id: '29',
    slug: 'carolina-panthers',
    abbreviation: 'CAR',
    location: 'Carolina',
    name: 'Panthers',
    displayName: 'Carolina Panthers',
    group: 'NFC South',
    color: '#0085ca',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/car.png',
  },
  {
    id: '3',
    slug: 'chicago-bears',
    abbreviation: 'CHI',
    location: 'Chicago',
    name: 'Bears',
    displayName: 'Chicago Bears',
    group: 'NFC North',
    color: '#0b1c3a',
    alternateColor: '#e64100',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/chi.png',
  },
  {
    id: '4',
    slug: 'cincinnati-bengals',
    abbreviation: 'CIN',
    location: 'Cincinnati',
    name: 'Bengals',
    displayName: 'Cincinnati Bengals',
    group: 'AFC North',
    color: '#fb4f14',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/cin.png',
  },
  {
    id: '5',
    slug: 'cleveland-browns',
    abbreviation: 'CLE',
    location: 'Cleveland',
    name: 'Browns',
    displayName: 'Cleveland Browns',
    group: 'AFC North',
    color: '#472a08',
    alternateColor: '#ff3c00',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/cle.png',
  },
  {
    id: '6',
    slug: 'dallas-cowboys',
    abbreviation: 'DAL',
    location: 'Dallas',
    name: 'Cowboys',
    displayName: 'Dallas Cowboys',
    group: 'NFC East',
    color: '#002a5c',
    alternateColor: '#b0b7bc',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/dal.png',
  },
  {
    id: '7',
    slug: 'denver-broncos',
    abbreviation: 'DEN',
    location: 'Denver',
    name: 'Broncos',
    displayName: 'Denver Broncos',
    group: 'AFC West',
    color: '#0a2343',
    alternateColor: '#fc4c02',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/den.png',
  },
  {
    id: '8',
    slug: 'detroit-lions',
    abbreviation: 'DET',
    location: 'Detroit',
    name: 'Lions',
    displayName: 'Detroit Lions',
    group: 'NFC North',
    color: '#0076b6',
    alternateColor: '#bbbbbb',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/det.png',
  },
  {
    id: '9',
    slug: 'green-bay-packers',
    abbreviation: 'GB',
    location: 'Green Bay',
    name: 'Packers',
    displayName: 'Green Bay Packers',
    group: 'NFC North',
    color: '#204e32',
    alternateColor: '#ffb612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/gb.png',
  },
  {
    id: '34',
    slug: 'houston-texans',
    abbreviation: 'HOU',
    location: 'Houston',
    name: 'Texans',
    displayName: 'Houston Texans',
    group: 'AFC South',
    color: '#021018',
    alternateColor: '#eb0028',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/hou.png',
  },
  {
    id: '11',
    slug: 'indianapolis-colts',
    abbreviation: 'IND',
    location: 'Indianapolis',
    name: 'Colts',
    displayName: 'Indianapolis Colts',
    group: 'AFC South',
    color: '#003b75',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/ind.png',
  },
  {
    id: '30',
    slug: 'jacksonville-jaguars',
    abbreviation: 'JAX',
    location: 'Jacksonville',
    name: 'Jaguars',
    displayName: 'Jacksonville Jaguars',
    group: 'AFC South',
    color: '#007487',
    alternateColor: '#d7a22a',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/jax.png',
  },
  {
    id: '12',
    slug: 'kansas-city-chiefs',
    abbreviation: 'KC',
    location: 'Kansas City',
    name: 'Chiefs',
    displayName: 'Kansas City Chiefs',
    group: 'AFC West',
    color: '#e31837',
    alternateColor: '#ffb612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/kc.png',
  },
  {
    id: '13',
    slug: 'las-vegas-raiders',
    abbreviation: 'LV',
    location: 'Las Vegas',
    name: 'Raiders',
    displayName: 'Las Vegas Raiders',
    group: 'AFC West',
    color: '#000000',
    alternateColor: '#a5acaf',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/lv.png',
  },
  {
    id: '24',
    slug: 'los-angeles-chargers',
    abbreviation: 'LAC',
    location: 'Los Angeles',
    name: 'Chargers',
    displayName: 'Los Angeles Chargers',
    group: 'AFC West',
    color: '#0080c6',
    alternateColor: '#ffc20e',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/lac.png',
  },
  {
    id: '14',
    slug: 'los-angeles-rams',
    abbreviation: 'LAR',
    location: 'Los Angeles',
    name: 'Rams',
    displayName: 'Los Angeles Rams',
    group: 'NFC West',
    color: '#003594',
    alternateColor: '#ffd100',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/lar.png',
  },
  {
    id: '15',
    slug: 'miami-dolphins',
    abbreviation: 'MIA',
    location: 'Miami',
    name: 'Dolphins',
    displayName: 'Miami Dolphins',
    group: 'AFC East',
    color: '#008e97',
    alternateColor: '#fc4c02',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/mia.png',
  },
  {
    id: '16',
    slug: 'minnesota-vikings',
    abbreviation: 'MIN',
    location: 'Minnesota',
    name: 'Vikings',
    displayName: 'Minnesota Vikings',
    group: 'NFC North',
    color: '#4f2683',
    alternateColor: '#ffc62f',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/min.png',
  },
  {
    id: '17',
    slug: 'new-england-patriots',
    abbreviation: 'NE',
    location: 'New England',
    name: 'Patriots',
    displayName: 'New England Patriots',
    group: 'AFC East',
    color: '#002a5c',
    alternateColor: '#c60c30',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/ne.png',
  },
  {
    id: '18',
    slug: 'new-orleans-saints',
    abbreviation: 'NO',
    location: 'New Orleans',
    name: 'Saints',
    displayName: 'New Orleans Saints',
    group: 'NFC South',
    color: '#d3bc8d',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/no.png',
  },
  {
    id: '19',
    slug: 'new-york-giants',
    abbreviation: 'NYG',
    location: 'New York',
    name: 'Giants',
    displayName: 'New York Giants',
    group: 'NFC East',
    color: '#003c7f',
    alternateColor: '#c9243f',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/nyg.png',
  },
  {
    id: '20',
    slug: 'new-york-jets',
    abbreviation: 'NYJ',
    location: 'New York',
    name: 'Jets',
    displayName: 'New York Jets',
    group: 'AFC East',
    color: '#115740',
    alternateColor: '#ffffff',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/nyj.png',
  },
  {
    id: '21',
    slug: 'philadelphia-eagles',
    abbreviation: 'PHI',
    location: 'Philadelphia',
    name: 'Eagles',
    displayName: 'Philadelphia Eagles',
    group: 'NFC East',
    color: '#06424d',
    alternateColor: '#000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/phi.png',
  },
  {
    id: '23',
    slug: 'pittsburgh-steelers',
    abbreviation: 'PIT',
    location: 'Pittsburgh',
    name: 'Steelers',
    displayName: 'Pittsburgh Steelers',
    group: 'AFC North',
    color: '#000000',
    alternateColor: '#ffb612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/pit.png',
  },
  {
    id: '25',
    slug: 'san-francisco-49ers',
    abbreviation: 'SF',
    location: 'San Francisco',
    name: '49ers',
    displayName: 'San Francisco 49ers',
    group: 'NFC West',
    color: '#aa0000',
    alternateColor: '#b3995d',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/sf.png',
  },
  {
    id: '26',
    slug: 'seattle-seahawks',
    abbreviation: 'SEA',
    location: 'Seattle',
    name: 'Seahawks',
    displayName: 'Seattle Seahawks',
    group: 'NFC West',
    color: '#002a5c',
    alternateColor: '#69be28',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/sea.png',
  },
  {
    id: '27',
    slug: 'tampa-bay-buccaneers',
    abbreviation: 'TB',
    location: 'Tampa Bay',
    name: 'Buccaneers',
    displayName: 'Tampa Bay Buccaneers',
    group: 'NFC South',
    color: '#bd1c36',
    alternateColor: '#3e3a35',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/tb.png',
  },
  {
    id: '10',
    slug: 'tennessee-titans',
    abbreviation: 'TEN',
    location: 'Tennessee',
    name: 'Titans',
    displayName: 'Tennessee Titans',
    group: 'AFC South',
    color: '#4495d2',
    alternateColor: '#001532',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/ten.png',
  },
  {
    id: '28',
    slug: 'washington-commanders',
    abbreviation: 'WSH',
    location: 'Washington',
    name: 'Commanders',
    displayName: 'Washington Commanders',
    group: 'NFC East',
    color: '#5a1414',
    alternateColor: '#ffb612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png',
    logoDark: 'https://a.espncdn.com/i/teamlogos/nfl/500-dark/wsh.png',
  },
];
